version = 1

test_patterns = ["testing/**"]

exclude_patterns = [
    "data/**",
    "experimental/**",
    "*.md"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true
