version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: /docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: /app/sources/frontend/app.py
    deploy:
      resources: 
        reservations:
          devices:
          - capabilities: [gpu]
            driver: nvidia